TEST_CATEGORY_TO_BODY_PARTS = {
    "Haematology": ["Blood", "Bone Marrow"],
    "Complete Blood Count": ["Blood"],
    "Liver Function Test": ["Liver", "Digestive System"],
    "Liver Function": ["Liver", "Digestive System"],
    "Kidney Function Test": ["Kidneys", "Urinary System"],
    "Kidney Function": ["Kidneys", "Urinary System"],
    "Lipid Profile": ["Blood", "Cardiovascular System", "Heart"],
    "Thyroid Profile": ["Thyroid", "Endocrine System"],
    "Thyroid Function": ["Thyroid", "Endocrine System"],
    "Blood Sugar": ["Blood", "Endocrine System", "Metabolism"],
    "Diabetes & Glucose": ["Blood", "Endocrine System", "Metabolism"],
    "Electrolytes": ["Blood", "Kidneys", "Metabolism"],
    "Urinalysis": ["Kidneys", "Urinary System"],
    "Cardiac Markers": ["Heart", "Cardiovascular System"],
    "Vitamins": ["Blood", "Nutritional Status", "Metabolism"],
    "Vitamins & Minerals": ["Blood", "Nutritional Status", "Metabolism"],
    "Hormone Profile": ["Endocrine System", "Metabolism"],
    "Hormones": ["Endocrine System", "Metabolism"],
    "Tumor Markers": ["Multiple Systems"],
    "Allergy Profile": ["Immune System", "Blood"],
    "Immunology": ["Immune System", "Blood"],
    "Coagulation Profile": ["Blood"],
    "Infectious Disease": ["Immune System", "Multiple Systems"],
    "Bone Profile": ["Bone", "Metabolism"],
    "Protein Profile": ["Blood", "Liver", "Nutritional Status"],
    "Proteins": ["Blood", "Liver", "Nutritional Status"],
    "Metabolic Panel": ["Metabolism", "Multiple Systems"],
    "Inflammatory Markers": ["Immune System", "Blood"],
    "Inflammation": ["Immune System", "Blood"],
    "Other": ["General"]
}

BODY_PARTS_TO_EMOJI = {
    "Blood": "🩸",
    "Bone Marrow": "🦴",
    "Liver": "🫁",
    "Digestive System": "�胃",
    "Kidneys": "🫘",
    "Urinary System": "💧",
    "Cardiovascular System": "❤️",
    "Heart": "❤️",
    "Thyroid": "🔄",
    "Endocrine System": "⚡",
    "Multiple Systems": "🔄",
    "Immune System": "🛡️",
    "Nutritional Status": "🥗",
    "General": "📊"
}

