TEST_CATEGORY_TO_BODY_PARTS = {
    "Haematology": ["Blood", "Bone Marrow"],
    "Complete Blood Count": ["Blood"],
    "Liver Function Test": ["Liver", "Digestive System"],
    "Kidney Function Test": ["Kidneys", "Urinary System"],
    "Lipid Profile": ["Blood", "Cardiovascular System", "Heart"],
    "Thyroid Profile": ["Thyroid", "Endocrine System"],
    "Blood Sugar": ["Blood", "Endocrine System", "Metabolism"],
    "Electrolytes": ["Blood", "Kidneys", "Metabolism"],
    "Urinalysis": ["Kidneys", "Urinary System"],
    "Cardiac Markers": ["Heart", "Cardiovascular System"],
    "Vitamins": ["Blood", "Nutritional Status", "Metabolism"],
    "Hormone Profile": ["Endocrine System", "Metabolism"],
    "Tumor Markers": ["Multiple Systems"],
    "Allergy Profile": ["Immune System", "Blood"],
    "Immunology": ["Immune System", "Blood"],
    "Coagulation Profile": ["Blood"],
    "Infectious Disease": ["Immune System", "Multiple Systems"],
    "Bone Profile": ["Bone", "Metabolism"],
    "Protein Profile": ["Blood", "Liver", "Nutritional Status"],
    "Metabolic Panel": ["Metabolism", "Multiple Systems"],
    "Inflammatory Markers": ["Immune System", "Blood"],
    "Other": ["General"]
}

# Map individual tests to categories
TEST_TO_CATEGORY = {
    "Haemoglobin": "Haematology",
    "Total Leucocyte Count": "Haematology",
    "Platelet Count": "Haematology",
    "Red Blood Cell Count": "Haematology",
    "White Blood Cell Count": "Haematology",
    "Neutrophils": "Haematology",
    "Lymphocytes": "Haematology",
    "Monocytes": "Haematology",
    "Eosinophils": "Haematology",
    "Basophils": "Haematology",
    "SGPT": "Liver Function Test",
    "SGOT": "Liver Function Test",
    "Alkaline Phosphatase": "Liver Function Test",
    "Bilirubin": "Liver Function Test",
    "Total Protein": "Protein Profile",
    "Albumin": "Protein Profile",
    "Globulin": "Protein Profile",
    "Creatinine": "Kidney Function Test",
    "Urea": "Kidney Function Test",
    "Uric Acid": "Kidney Function Test",
    "Cholesterol": "Lipid Profile",
    "Triglycerides": "Lipid Profile",
    "HDL": "Lipid Profile",
    "LDL": "Lipid Profile",
    "TSH": "Thyroid Profile",
    "T3": "Thyroid Profile",
    "T4": "Thyroid Profile",
    "Glucose": "Blood Sugar",
    "HbA1c": "Blood Sugar",
    "Vitamin B12": "Vitamins",
    "Vitamin D": "Vitamins",
    "Vitamin B9": "Vitamins",
    "Folate": "Vitamins",
    "Calcium": "Bone Profile",
    "Phosphorus": "Bone Profile",
    "Magnesium": "Electrolytes",
    "Sodium": "Electrolytes",
    "Potassium": "Electrolytes",
    "Chloride": "Electrolytes",
    "CRP": "Inflammatory Markers",
    "ESR": "Inflammatory Markers",
    "Iron": "Haematology",
    "Ferritin": "Haematology",
}

BODY_PARTS_TO_EMOJI = {
    "Blood": "🩸",
    "Bone Marrow": "🦴",
    "Liver": "🫁",
    "Digestive System": "�胃",
    "Kidneys": "🫘",
    "Urinary System": "💧",
    "Cardiovascular System": "❤️",
    "Heart": "❤️",
    "Thyroid": "🔄",
    "Endocrine System": "⚡",
    "Multiple Systems": "🔄",
    "Immune System": "🛡️",
    "Nutritional Status": "🥗",
    "General": "📊"
}
