-- Firebase + PostgreSQL bootstrap schema for Medical Project.
-- This migration is Supabase-agnostic: it does NOT reference auth.users.
-- Safe to run multiple times (idempotent where possible).

CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- ── Core auth/user table (Firebase identity mapped to local user row) ─────────

CREATE TABLE IF NOT EXISTS users (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  firebase_uid VARCHAR(128) NOT NULL UNIQUE,
  email VARCHAR(256) NULL,
  display_name VARCHAR(256) NULL,
  is_admin BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  last_login TIMESTAMP NOT NULL DEFAULT NOW()
);

ALTER TABLE users
  ADD COLUMN IF NOT EXISTS firebase_uid VARCHAR(128),
  ADD COLUMN IF NOT EXISTS email VARCHAR(256),
  ADD COLUMN IF NOT EXISTS display_name VARCHAR(256),
  ADD COLUMN IF NOT EXISTS is_admin BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  ADD COLUMN IF NOT EXISTS last_login TIMESTAMP NOT NULL DEFAULT NOW();

DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'users' AND column_name = 'firebase_uid'
  ) AND NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'uq_users_firebase_uid'
  ) THEN
    ALTER TABLE users
    ADD CONSTRAINT uq_users_firebase_uid UNIQUE (firebase_uid);
  END IF;
END
$$;

CREATE INDEX IF NOT EXISTS idx_users_firebase_uid ON users(firebase_uid);
CREATE INDEX IF NOT EXISTS idx_users_last_login ON users(last_login DESC);
CREATE INDEX IF NOT EXISTS idx_users_is_admin ON users(is_admin);

-- ── Saved analysis history ───────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS report_analyses (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  firebase_uid VARCHAR(128) NOT NULL,
  patient_name VARCHAR(256) NULL,
  patient_age VARCHAR(64) NULL,
  patient_gender VARCHAR(64) NULL,
  patient_id VARCHAR(128) NULL,
  lab_name VARCHAR(512) NULL,
  report_date VARCHAR(64) NULL,
  total_records INTEGER NOT NULL DEFAULT 0,
  analysis_json TEXT NOT NULL,
  source_filenames TEXT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT NOW()
);

ALTER TABLE report_analyses
  ADD COLUMN IF NOT EXISTS firebase_uid VARCHAR(128),
  ADD COLUMN IF NOT EXISTS patient_name VARCHAR(256),
  ADD COLUMN IF NOT EXISTS patient_age VARCHAR(64),
  ADD COLUMN IF NOT EXISTS patient_gender VARCHAR(64),
  ADD COLUMN IF NOT EXISTS patient_id VARCHAR(128),
  ADD COLUMN IF NOT EXISTS lab_name VARCHAR(512),
  ADD COLUMN IF NOT EXISTS report_date VARCHAR(64),
  ADD COLUMN IF NOT EXISTS total_records INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS analysis_json TEXT,
  ADD COLUMN IF NOT EXISTS source_filenames TEXT,
  ADD COLUMN IF NOT EXISTS created_at TIMESTAMP NOT NULL DEFAULT NOW();

CREATE INDEX IF NOT EXISTS idx_report_analyses_firebase_uid ON report_analyses(firebase_uid);
CREATE INDEX IF NOT EXISTS idx_report_analyses_created_at ON report_analyses(created_at DESC);

-- ── Study management tables ──────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS profiles (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  account_owner_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  full_name VARCHAR(256) NOT NULL,
  relationship VARCHAR(64) NOT NULL,
  date_of_birth DATE NULL,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);

ALTER TABLE profiles
  ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP NOT NULL DEFAULT NOW();

CREATE INDEX IF NOT EXISTS idx_profiles_account_owner_id ON profiles(account_owner_id);

CREATE TABLE IF NOT EXISTS studies (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  profile_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  name VARCHAR(256) NOT NULL,
  description TEXT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'uq_studies_profile_name'
  ) THEN
    ALTER TABLE studies
    ADD CONSTRAINT uq_studies_profile_name UNIQUE (profile_id, name);
  END IF;
END
$$;

CREATE INDEX IF NOT EXISTS idx_studies_profile_id ON studies(profile_id);
CREATE INDEX IF NOT EXISTS idx_studies_updated_at ON studies(updated_at DESC);

CREATE TABLE IF NOT EXISTS reports (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  study_id UUID NOT NULL REFERENCES studies(id) ON DELETE CASCADE,
  file_name VARCHAR(512) NOT NULL,
  file_url TEXT NOT NULL,
  report_date DATE NOT NULL,
  lab_name VARCHAR(512) NULL,
  analysis_data JSONB NOT NULL,
  normalized_records JSONB NULL,
  is_normalized BOOLEAN NOT NULL DEFAULT FALSE,
  normalization_version INTEGER NULL,
  uploaded_at TIMESTAMP NOT NULL DEFAULT NOW()
);

ALTER TABLE reports
  ADD COLUMN IF NOT EXISTS normalized_records JSONB,
  ADD COLUMN IF NOT EXISTS is_normalized BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS normalization_version INTEGER;

CREATE INDEX IF NOT EXISTS idx_reports_study_id ON reports(study_id);
CREATE INDEX IF NOT EXISTS idx_reports_report_date ON reports(report_date);
CREATE INDEX IF NOT EXISTS idx_reports_uploaded_at ON reports(uploaded_at DESC);

-- ── Validation metrics table (Firebase + PostgreSQL) ─────────────────────────

CREATE TABLE IF NOT EXISTS metrics (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  metric_name TEXT NOT NULL,
  value NUMERIC NOT NULL,
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  user_id INTEGER NULL REFERENCES users(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_metrics_metric_name_created_at
  ON metrics (metric_name, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_metrics_user_id_created_at
  ON metrics (user_id, created_at DESC);

ALTER TABLE metrics ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS metrics_admin_read ON metrics;
CREATE POLICY metrics_admin_read ON metrics
  FOR SELECT
  USING (
    COALESCE(current_setting('app.is_admin', true), 'false')::boolean = true
  );

DROP POLICY IF EXISTS metrics_service_insert ON metrics;
CREATE POLICY metrics_service_insert ON metrics
  FOR INSERT
  WITH CHECK (true);

-- ── Updated-at triggers ──────────────────────────────────────────────────────

CREATE OR REPLACE FUNCTION set_row_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_profiles_set_updated_at ON profiles;
CREATE TRIGGER trg_profiles_set_updated_at
BEFORE UPDATE ON profiles
FOR EACH ROW
EXECUTE FUNCTION set_row_updated_at();

DROP TRIGGER IF EXISTS trg_studies_set_updated_at ON studies;
CREATE TRIGGER trg_studies_set_updated_at
BEFORE UPDATE ON studies
FOR EACH ROW
EXECUTE FUNCTION set_row_updated_at();

-- Keep study.updated_at in sync when reports change.
CREATE OR REPLACE FUNCTION touch_study_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  IF TG_OP = 'DELETE' THEN
    UPDATE studies SET updated_at = NOW() WHERE id = OLD.study_id;
    RETURN OLD;
  END IF;

  UPDATE studies SET updated_at = NOW() WHERE id = NEW.study_id;

  IF TG_OP = 'UPDATE' AND NEW.study_id IS DISTINCT FROM OLD.study_id THEN
    UPDATE studies SET updated_at = NOW() WHERE id = OLD.study_id;
  END IF;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_touch_study_updated_at ON reports;
CREATE TRIGGER trg_touch_study_updated_at
AFTER INSERT OR UPDATE OR DELETE ON reports
FOR EACH ROW
EXECUTE FUNCTION touch_study_updated_at();
